const SPOTIFY_CLIENT_ID_SECRET = "SPOTIFY_CLIENT_ID";
const SPOTIFY_CLIENT_SECRET_SECRET = "SPOTIFY_CLIENT_SECRET";
const SONG_OF_THE_DAY_ADMIN_TOKEN_SECRET = "SONG_OF_THE_DAY_ADMIN_TOKEN";

const SPOTIFY_CLIENT_ID = process.env.SPOTIFY_CLIENT_ID ?? "";
const SPOTIFY_CLIENT_SECRET = process.env.SPOTIFY_CLIENT_SECRET ?? "";
const SPOTIFY_PLAYLIST_ID = process.env.SPOTIFY_PLAYLIST_ID ?? "";
const SONG_OF_THE_DAY_ADMIN_TOKEN =
  process.env.SONG_OF_THE_DAY_ADMIN_TOKEN ?? "";
const FIREBASE_CONFIG = process.env.FIREBASE_CONFIG;
const FIREBASE_PROJECT_ID = FIREBASE_CONFIG ?
  (JSON.parse(FIREBASE_CONFIG).projectId as string | undefined) ?? "" :
  "";
const GCLOUD_PROJECT =
  process.env.GCLOUD_PROJECT ??
  process.env.GCLOUD_PROJECT_NUMBER ??
  FIREBASE_PROJECT_ID;

const REGION = "us-central1";
const SONG_OF_THE_DAY_TIMEZONE =
    process.env.SONG_OF_THE_DAY_TIMEZONE ?? "America/Costa_Rica";

const REDIRECT_URI_LOCAL =
    `http://127.0.0.1:5001/${GCLOUD_PROJECT}/${REGION}/spotifyCallback`;
const REDIRECT_URI_PROD =
    `https://${REGION}-${GCLOUD_PROJECT}.cloudfunctions.net/spotifyCallback`;

export {
  GCLOUD_PROJECT,
  REDIRECT_URI_LOCAL,
  REDIRECT_URI_PROD,
  REGION,
  SONG_OF_THE_DAY_TIMEZONE,
  SONG_OF_THE_DAY_ADMIN_TOKEN,
  SONG_OF_THE_DAY_ADMIN_TOKEN_SECRET,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  SPOTIFY_CLIENT_ID_SECRET,
  SPOTIFY_CLIENT_SECRET_SECRET,
  SPOTIFY_PLAYLIST_ID,
};
